/* eslint-disable no-console */
import { resolve } from 'path';
import { format, resolveConfig } from 'prettier';
import fs from 'fs-extra';
import dedent from 'dedent';
import chalk from 'chalk';
import fg from 'fast-glob';
import { camelCase } from 'lodash-es';

export const generateInjectables = async () => {
  const injectables = (await fg('**/*.injectable.ts')).map(path => ({
    name: camelCase(
      path.slice(path.lastIndexOf('/') + 1).replace('.injectable.ts', '')
    ),
    importPath: path.replace('src', '@').replace('.ts', '')
  }));

  const importBlocks = injectables.map(
    ({ name, importPath }) => `import ${name} from '${importPath}';`
  );

  const injectablesBlocks = injectables.map(({ name }) => {
    return dedent`${name}: register(${name})`;
  });

  const outputPath = resolve(process.cwd(), 'src/generated/injectables.ts');
  fs.ensureFileSync(outputPath);

  const template = dedent`
  /* 
    THIS IS A GENERATED FILE. DO NOT EInjectablesT
    This file is automatically generated when bootstraping the application
  */
  import { asFunction, asValue } from 'awilix';
  ${importBlocks.join('\n')}
  
  const register = (val: any) => typeof val === 'function' ? asFunction(val) : asValue(val)

  export const injectables = {
    ${injectablesBlocks.join(',\n\t')}
  } as const;
  `;

  console.log(chalk.green('[  DI  ]'), ' - Injectables generated.');

  fs.writeFileSync(
    outputPath,
    format(template, {
      ...(await resolveConfig(outputPath)),
      parser: 'typescript'
    })
  );
};
